### ISSUE TITLE
feat: add support for `resolve` drop-in replacement

### ISSUE THREAD

**Issue by titanism** [Kikobeats/doh-resolver#16]
Right now we can use this for `resolve4` and `resolve6`, but not `resolve`.  Can this be added?

We would gladly sponsor your efforts on GitHub Sponsors.

**Comment by Kikobeats** [comment]
@titanism I guess you closed this because you see the example on the README 🙂

**Comment by Kikobeats** [comment]
> No, we're actually not using this project anymore because the Packet implementation is not up to par.

Can you explain that? what's wrong in the `Packet` implementation provided by dns2?

**Comment by Kikobeats** [comment]
unfortunately, I can't use it – forcing to use a specific HTTP client is too inflexible to support real use cases, undici adoption is almost insignificant compared with axios, got, etc.
